# Site settings
theme: jekyll-theme-minimal
title: Ted Ogmundson
logo: /images/headshot.png
description: "I'm Ted. A Full Stack Web Developer, an aspiring birdwatcher, and a person who likes to play with systems. An avid problem-solver who loves the thrilling pace of a startup and the deeply collaborative culture of tech."
