# Site settings
title: Ted Ogmundson
logo: /headshot.png
email: togmund@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Ted. A Rad Guy.
  604-600-6867
  [LinkedIn](https://ca.linkedin.com/in/ted-ogmundson-1a9b47a)
baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: togmund
github_username:  togmund
linkedin_username: ted-ogmundson

theme: jekyll-theme-minimal