# Site settings
theme: jekyll-theme-minimal
title: Ted Ogmundson
logo: /assets/img/logo.png
description: > # this means to ignore newlines until "baseurl:"
  I'm Ted. A Rad Guy.
  604-600-6867
email: togmund@gmail.com