# Site settings
theme: jekyll-theme-minimal
title: Ted Ogmundson
logo: /images/headshot.png
description: "I'm Ted.

I'm a Full Stack Web Developer, an aspiring birdwatcher, and a person who likes to play with systems.

I'm an avid problem-solver who loves the frenetic pace of a startup and the deeply collaborative culture of tech."
