title: Ted Ogmundson
logo: headshot.png
description: I'm Ted. A Rad Guy.
email: togmund@gmail.com
phone: 604-600-6867
LinkedIn: [LinkedIn](https://ca.linkedin.com/in/ted-ogmundson-1a9b47a)
theme: jekyll-theme-minimal